# println("Johan/emission_comparison.jl")
# include("Johan/emission_comparison.jl")
# println("Johan/iron_line_comparison_approx.jl")
# include("Johan/iron_line_comparison_approx.jl")
# println("Johan/temperature_renders.jl")
# include("Johan/temperature_renders.jl")
# println("Others/ISCO_spin.jl")
# include("Others/ISCO_spin.jl")
println("PT/iron_lines/iron_heatmap.jl")
include("PT/iron_lines/iron_heatmap.jl")
# println("PT/iron_lines/iron_line_basic.jl")
# include("PT/iron_lines/iron_line_basic.jl")
println("PT/iron_lines/iron_line_combined.jl")
include("PT/iron_lines/iron_line_combined.jl")
println("PT/iron_lines/iron_line_comparison.jl")
include("PT/iron_lines/iron_line_comparison.jl")
println("PT/renders/renders_parameters.jl")
include("PT/renders/renders_parameters.jl")